### ISSUE TITLE
when php file have function ,after copy nodes.csv and rels.csv to joern-navex which generate by phpjoern, it report exception as follows  when use './phpast2cpg nodes.csv rels.csv' command

### ISSUE THREAD

**Issue by lujunsincerely** [aalhuz/navex#4]
Exception in thread "main" java.lang.ClassCastException: ast.expressions.StringExpression cannot be cast to ast.functionDef.ParameterList
	at tools.php.ast2cpg.PHPCSVEdgeInterpreter.handleFunction(PHPCSVEdgeInterpreter.java:540)
	at tools.php.ast2cpg.PHPCSVEdgeInterpreter.handle(PHPCSVEdgeInterpreter.java:162)
	at inputModules.csv.csv2ast.CSV2AST.createASTEdges(CSV2AST.java:85)
	at inputModules.csv.csv2ast.CSV2AST.convert(CSV2AST.java:48)
	at inputModules.csv.csvFuncExtractor.CSVFunctionExtractor.getNextFunction(CSVFunctionExtractor.java:72)
	at tools.php.ast2cpg.Main.main(Main.java:76)

**Comment by jo285317** [comment]
any updates?

**Comment by AlisonBrie** [comment]
Anyone manage to fix this?

**Comment by SheltonShi** [comment]
I encountered the same problem

**Comment by JulianGR** [comment]
I managed to fix it and I created a PR in the original repo, see [https://github.com/malteskoruppa/phpjoern/issues/2#issuecomment-617334737](https://github.com/malteskoruppa/phpjoern/issues/2#issuecomment-617334737)

**Comment by sukwon0709** [comment]
Use v0.1.2 for php-ast.

**Comment by peng-hui** [comment]
Unfortunately, this answer is not correct. @JulianGR 
> I managed to fix it and I created a PR in the original repo, see [malteskoruppa/phpjoern#2 (comment)](https://github.com/malteskoruppa/phpjoern/issues/2#issuecomment-617334737)

Using PHPJoern to export `node.csv` and `edges.csv`, the headers should be consistent with `joern/projects/extensions/joern-php/src/main/java/inputModules/csv/PHPCSVEdgeTypes.java` and `joern/projects/extensions/joern-php/src/main/java/inputModules/csv/PHPCSVNodeTypes.java` instead of the ones required by the noe4j graph database.  So the result csv files are in correct and consistent formats. 


-----
> Use v0.1.2 for php-ast.

Instead, this is the correct answer and can successfully export `cpg_edges.csv`.

However, the code of NAVEX is incomplete. Several functions that perform graph database traverse are not provided in the source. Ultimately, it is impossible to reproduce NAVEX. (I have tried that.)
It is not suggested to spend too much time on NAVEX unless you write your own traverse scripts.
