### ISSUE TITLE
com.tinkerpop.gremlin.groovy.GremlinGroovyPipeline.includeMap() is applicable for argument

### ISSUE THREAD

**Issue by ghost** [aalhuz/navex#5]
1. I run `python static-main.py`
some errors in `Analysis.py`  and i reformat  `Analysis.py` 

2.then run `python static-main.py`
i got some thing wrong like `isCallExpression(it.nameToCall().next()) }.callexpressions()`

3. and I modify  `DEFAULT_STEP_DIR = os.path.dirname(__file__) + '/phpjoernsteps/'` in `joern/all.py`
but  i  got another error :
`sudo python static-main.py sql`
```
the query is 
xss_funcs = [
                "print", "echo"
                ]
sql_query_funcs = [
                "mysql_query", "mysqli_query", "pg_query", "sqlite_query"
                ]
os_command_funcs = [
               "backticks", "exec" , "expect_popen","passthru","pcntl_exec",
               "popen","proc_open","shell_exec","system", "mail"     
               ]
  m =[];  queryMapList =[]; g.V().filter{sql_query_funcs.contains(it.code)  && isCallExpression(it.nameToCall().next()) }.callexpressions()
                            .sideEffect{m = start(it, [], 0, 'sql', false, queryMapList)}
                            .sideEffect{ warnmessage = warning(it.toFileAbs().next().name, it.lineno, it.id, 'sql', '1')}
                            .sideEffect{ reportmessage = report(it.toFileAbs().next().name, it.lineno, it.id)}
                            .ifThenElse{m.isEmpty()}
                              {it.transform{reportmessage}}
                              {it.transform{findSinkLocation(m, warnmessage, 'sql', queryMapList, it)}}
                            
                           
        
                      
[]
Caught exception: <class 'py2neo.error.BadInputException'> javax.script.ScriptException: groovy.lang.MissingMethodException: No signature of method: com.tinkerpop.gremlin.groovy.GremlinGroovyPipeline.includeMap() is applicable for argument types: () values: []
Traceback (most recent call last):
  File "static-main.py", line 64, in <module>
    main(sys.argv)
  File "static-main.py", line 26, in main
    writeIncludeMapToFile(result, elapsed_time)
  File "static-main.py", line 55, in writeIncludeMapToFile
    for node in result:
TypeError: 'NoneType' object is not iterable
```

**Comment by ghost** [comment]
this error due to
`result, elapsed_time =sa.runTimedQuery("g.V().includeMap()")`  in `static-main.py:25`
this `includeMap` function not found in `https://github.com/aalhuz/python-joern/tree/navex`

**Comment by EdoardoVignati** [comment]
Hi @UUUUnotfound, I'm facing the same problem. Did you find a solution for this error?

**Comment by ghost** [comment]
> Hi @UUUUnotfound, I'm facing the same problem. Did you find a solution for this error?

You can view my repo <https://github.com/UUUUnotfound/Navex_fixed>
I fixed it.
